const bformActionTypes = {
    CALL_REV_GEO: 'CALL_REV_GEO',
    GET_URL_PARAMS: 'GET_URL_PARAMS',
    PASS_URL_PARAMS: 'PASS_URL_PARAMS',
    SEARCH_AUTOCOMPLETE : 'SEARCH_AUTOCOMPLETE',
    SEARCH_SELECT_PLACE : 'SEARCH_SELECT_PLACE',
    GET_NEARBY_PLACES_BY_CATEGORY : 'GET_NEARBY_PLACES_BY_CATEGORY'
};
  
  export default bformActionTypes;
  